name: Test Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests with coverage
      run: npm run test:coverage
    
    - name: Install istanbul reports
      run: npm install -g istanbul-reports
    
    - name: Generate coverage summary
      run: |
        # If coverage-summary.json doesn't exist but coverage-final.json does, create it
        if [ -f "coverage/coverage-final.json" ] && [ ! -f "coverage/coverage-summary.json" ]; then
          npx istanbul report json-summary --include coverage/coverage-final.json --dir coverage/
        fi
    
    - name: Update coverage badge
      if: github.ref == 'refs/heads/main'
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "chore: update coverage metrics [skip ci]"
        file_pattern: coverage/coverage-summary.json