name: Test Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Explicitly define permissions
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests with coverage
      run: npm run test:coverage
    
    - name: Generate coverage summary and badge
      run: |
        # Create the coverage directory if it doesn't exist
        mkdir -p coverage
        
        # Generate the coverage summary JSON
        npx istanbul report json-summary --include coverage/coverage-final.json --dir coverage/
        
        # Extract coverage percentage
        COVERAGE=$(node -e "console.log(JSON.parse(require('fs').readFileSync('./coverage/coverage-summary.json')).total.statements.pct)")
        
        # Create a badge SVG file directly using shields.io static URL (no dynamic processing needed)
        echo "Coverage: $COVERAGE%"
        
        # Create a README badge using shields.io static badge
        sed -i "s|https://raw.githubusercontent.com/unctad-ai/eregulations-mcp-server/main/coverage/badge.svg|https://img.shields.io/badge/coverage-${COVERAGE}%25-$(node -e \"const cov = $COVERAGE; console.log(cov > 80 ? 'brightgreen' : cov > 70 ? 'green' : cov > 60 ? 'yellowgreen' : cov > 50 ? 'yellow' : 'red')\")|g" README.md
    
    - name: Commit updated README
      if: github.ref == 'refs/heads/main'
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "chore: update coverage badge in README [skip ci]"
        file_pattern: "README.md"