name: Test Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests with coverage
      run: npm run test:coverage
    
    - name: Generate coverage summary and badge
      run: |
        # Create the coverage directory if it doesn't exist
        mkdir -p coverage
        
        # Generate the coverage summary JSON
        npx istanbul report json-summary --include coverage/coverage-final.json --dir coverage/
        
        # Extract coverage percentage
        COVERAGE=$(node -e "console.log(JSON.parse(require('fs').readFileSync('./coverage/coverage-summary.json')).total.statements.pct)")
        
        # Create a badge SVG file
        COLOR=$(node -e "const cov = $COVERAGE; console.log(cov > 80 ? 'brightgreen' : cov > 70 ? 'green' : cov > 60 ? 'yellowgreen' : cov > 50 ? 'yellow' : 'red')")
        curl -s "https://img.shields.io/badge/coverage-${COVERAGE}%25-${COLOR}" > coverage/badge.svg
    
    - name: Commit coverage files
      if: github.ref == 'refs/heads/main'
      uses: EndBug/add-and-commit@v9
      with:
        add: 'coverage/coverage-summary.json coverage/badge.svg --force'
        message: 'chore: update coverage metrics [skip ci]'
        push: true
        default_author: github_actions