name: Test Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Explicitly define permissions
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Generate coverage summary and badge
      run: |
        # No need to create coverage directory for badge purposes
        
        # Extract coverage percentage from coverage report
        npm run test:coverage || true
        COVERAGE=$(cat coverage/coverage-final.json | grep -o '"statements":{"total":[0-9]*,"covered":[0-9]*,"pct":[0-9.]*' | grep -o 'pct":[0-9.]*' | grep -o '[0-9.]*' | head -n 1)
        
        # Create a badge SVG file directly using shields.io static URL (no dynamic processing needed)
        echo "Coverage: $COVERAGE%"
        
        # Determine color based on coverage
        if (( $(echo "$COVERAGE > 80" | bc -l) )); then
          COLOR="brightgreen"
        elif (( $(echo "$COVERAGE > 70" | bc -l) )); then
          COLOR="green"
        elif (( $(echo "$COVERAGE > 60" | bc -l) )); then
          COLOR="yellowgreen"
        elif (( $(echo "$COVERAGE > 50" | bc -l) )); then
          COLOR="yellow"
        else
          COLOR="red"
        fi
        
        # Create a README badge using shields.io static badge
        sed -i "s|https://img.shields.io/badge/coverage-[0-9.]*%25-[a-z]*|https://img.shields.io/badge/coverage-${COVERAGE}%25-${COLOR}|g" README.md
    
    - name: Commit updated README
      if: github.ref == 'refs/heads/main'
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "chore: update coverage badge in README [skip ci]"
        file_pattern: "README.md"